CREATE TABLE IF NOT EXISTS MEMBERS (
    MNAME    VARCHAR(50)  NOT NULL,
	PWD      VARCHAR(100) NOT NULL,

	PRIMARY KEY(MNAME)
);

CREATE TABLE IF NOT EXISTS AUTHORITIES (
    MNAME     VARCHAR(50)  NOT NULL,
    AUTHORITY VARCHAR(50)  NOT NULL,

    PRIMARY KEY(MNAME)
);

MERGE INTO MEMBERS VALUES ( 'admin',  '12345' );
MERGE INTO MEMBERS VALUES ( 'member', '67890' );
MERGE INTO MEMBERS VALUES ( 'guest', 'abcde'  );

-- TODO : #13 PAYCO ID 계정 추가
MERGE INTO MEMBERS VALUES ( 'dongmyo@nhnent.com', '');

MERGE INTO AUTHORITIES VALUES ( 'admin' , 'ROLE_ADMIN'  );
MERGE INTO AUTHORITIES VALUES ( 'member', 'ROLE_MEMBER' );
MERGE INTO AUTHORITIES VALUES ( 'guest' , 'ROLE_GUEST'  );

-- TODO : #13 PAYCO ID 계정 추가
MERGE INTO AUTHORITIES VALUES ( 'dongmyo@nhnent.com' , 'ROLE_GUEST');

